- hosts: localhost
  name: configuration
  user: ec2-user
  become: yes
  become_user: root
  gather_facts: true

  tasks:
          -   name: Install python setup tools
              yum: name=python-setuptools
              tags: docker

          -   name: Install git
              yum: name=git
              tags: docker

          -   name: Install Pypi
              easy_install: name=pip
              tags: docker

          -   name: Install docker-py
              pip: name=docker-py
              tags: docker

          -   name: Install Docker
              yum: name=docker state=latest
              tags: docker

          -   name: Ensure ec2-user is member of docker group
              user:
                name=ec2-user
                groups=wheel,docker

          -   name: Make sure Docker is running
              service: name=docker state=running enabled=yes
              tags: docker

          -   name: Install -> Docker-Compose
              sudo: yes
              get_url:
                url=https://github.com/docker/compose/releases/download/1.11.2/docker-compose-Linux-x86_64
                dest=/usr/local/bin/docker-compose
                mode=0755

          -   name: setup directory for mozilla-projects
              sudo: yes
              file:
                path=/opt/mozilla-projects
                state=directory
                mode=770

          -   name: Ensure ansible-container on system
              pip: name=ansible-container
              tags: docker

          -   name: Install Amazon MetaData tools
              sudo: yes
              get_url:
                url=http://s3.amazonaws.com/ec2metadata/ec2-metadata
                dest=/usr/local/bin/ec2-metadata
                mode=0755

          -   name: Install jq
              yum: name=jq
              tags: docker

          -   name: Install Lego Cert Client
              get_url:
                url=https://github.com/xenolf/lego/releases/download/v0.3.1/lego_linux_amd64.tar.xz
                dest=/home/ec2-user/lego_linux_amd64.tar.xz
                mode=0755

          -   name: unarchive lego client
              sudo: yes
              unarchive:
                src=/home/ec2-user/lego_linux_amd64.tar.xz
                dest=/opt/

          -   name: easy_install supervisor
              sudo: yes
              easy_install: name=supervisor

          -   name: install credstash
              pip: name=credstash
